# Minimal makefile for Flutter documentation
#

#The following commands should be executed after the files from git are downloaded
#

Flutter doctor, #used to make sure all necessary tools are downloaded
flutter pub get, #forces flutter to search for and install dependenies in the .yaml file
flutter build, #builds the current version of the project.

after having fetched the dependencies and built the project,
use flutter run to run the program
