# Minimal makefile for Flutter documentation
#

#The following commands should be executed after the files from git are downloaded
#

Flutter doctor,
flutter pub get,
flutter build

after having fetched the dependencies and built the project,
use flutter run to run the program
